version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: Thermometer_Ninja
      POSTGRES_PASSWORD: HotCocoa42
      POSTGRES_DB: Thermal_Rising
